#!/bin/bash

dir="$1"

read -p "Will remove recursively $dir (Y/n): " answer
test "$answer" != "Y" -a "$answer" != "y" -a "$answer" != "" && exit 1
find "$dir" -type d -print0 | xargs -0 chmod 755
find "$dir" -type f -print0 | xargs -0 chmod 644
rm -rf "$dir"
